var L_privacy_s5 = {
  en:      { heading: '5. Third-Party Services',  body: 'Roulette de Movie uses no third-party analytics, advertising, or crash-reporting SDKs. The app is built entirely on Apple\'s native frameworks. The only third-party interaction is the movie search API described in Section 4.' },
  ar:      { heading: '5. خدمات الجهات الخارجية', body: 'لا يستخدم Roulette de Movie أي حزم SDK للتحليلات أو الإعلانات أو الإبلاغ عن الأعطال من جهات خارجية. التطبيق مبني بالكامل على أطر عمل Apple الأصلية. التفاعل الوحيد مع جهات خارجية هو واجهة برمجة تطبيقات البحث عن الأفلام الموضحة في القسم 4.' },
  'zh-Hans': { heading: '5. 第三方服务',           body: 'Roulette de Movie 不使用任何第三方分析、广告或崩溃报告 SDK。该应用完全基于 Apple 的原生框架构建。唯一的第三方交互是第 4 节中描述的电影搜索 API。' },
  nl:      { heading: '5. Diensten van derden',   body: 'Roulette de Movie gebruikt geen analytics-, reclame- of crashrapportage-SDK\'s van derden. De app is volledig gebouwd op Apple\'s native frameworks. De enige interactie met derden is de filmzoek-API die in sectie 4 wordt beschreven.' },
  fr:      { heading: '5. Services tiers',        body: 'Roulette de Movie n\'utilise aucun SDK tiers d\'analyse, de publicité ou de rapport de plantage. L\'application est entièrement construite sur les frameworks natifs d\'Apple. La seule interaction tierce est l\'API de recherche de films décrite à la section 4.' },
  de:      { heading: '5. Dienste Dritter',       body: 'Roulette de Movie verwendet keine Analyse-, Werbe- oder Absturzbericht-SDKs von Drittanbietern. Die App basiert vollständig auf Apples nativen Frameworks. Die einzige Interaktion mit Dritten ist die in Abschnitt 4 beschriebene Filmsuche-API.' },
  it:      { heading: '5. Servizi di terze parti', body: 'Roulette de Movie non utilizza SDK di terze parti per analisi, pubblicità o segnalazione di arresti anomali. L\'app è interamente costruita sui framework nativi di Apple. L\'unica interazione con terze parti è l\'API di ricerca film descritta nella sezione 4.' },
  ko:      { heading: '5. 제3자 서비스',            body: 'Roulette de Movie는 제3자 분석, 광고 또는 충돌 보고 SDK를 사용하지 않습니다. 앱은 전적으로 Apple의 네이티브 프레임워크로 구축되었습니다. 유일한 제3자 상호작용은 섹션 4에 설명된 영화 검색 API입니다.' },
  'pt-PT': { heading: '5. Serviços de Terceiros', body: 'O Roulette de Movie não utiliza SDKs de terceiros para análises, publicidade ou relatórios de falhas. A aplicação é construída inteiramente nos frameworks nativos da Apple. A única interação com terceiros é a API de pesquisa de filmes descrita na Secção 4.' },
  es:      { heading: '5. Servicios de Terceros', body: 'Roulette de Movie no utiliza SDKs de terceros para análisis, publicidad ni informes de fallos. La aplicación está construida íntegramente sobre los frameworks nativos de Apple. La única interación con terceros es la API de búsqueda de películas descrita en la Sección 4.' }
};
