var L_privacy_s8 = {
  en:      { heading: '8. Your Rights',    body: 'Since we store no data about you on any server, there is nothing for us to access, export, or delete on your behalf. To remove all data associated with the app, use the delete option within the app or uninstall Roulette de Movie from your device.' },
  ar:      { heading: '8. حقوقك',          body: 'بما أننا لا نخزّن أي بيانات عنك على أي خادم، فلا يوجد ما يمكننا الوصول إليه أو تصديره أو حذفه نيابةً عنك. لإزالة جميع البيانات المرتبطة بالتطبيق، استخدم خيار الحذف داخل التطبيق أو قم بإلغاء تثبيت Roulette de Movie من جهازك.' },
  'zh-Hans': { heading: '8. 您的权利',      body: '由于我们不在任何服务器上存储您的数据，因此没有任何内容需要我们代您访问、导出或删除。如需删除与应用相关的所有数据，请使用应用内的删除选项或从您的设备上卸载 Roulette de Movie。' },
  nl:      { heading: '8. Jouw rechten',   body: 'Omdat we geen gegevens over jou op een server opslaan, is er niets dat we namens jou kunnen inzien, exporteren of verwijderen. Om alle gegevens van de app te verwijderen, gebruik je de verwijderoptie in de app of verwijder je Roulette de Movie van je apparaat.' },
  fr:      { heading: '8. Vos droits',     body: 'Comme nous ne stockons aucune donnée vous concernant sur un serveur, il n'y a rien à consulter, exporter ou supprimer en votre nom. Pour supprimer toutes les données associées à l'application, utilisez l'option de suppression dans l'application ou désinstallez Roulette de Movie de votre appareil.' },
  de:      { heading: '8. Deine Rechte',   body: 'Da wir keine Daten über dich auf einem Server speichern, gibt es nichts, das wir in deinem Auftrag einsehen, exportieren oder löschen könnten. Um alle mit der App verbundenen Daten zu entfernen, verwende die Löschoption in der App oder deinstalliere Roulette de Movie von deinem Gerät.' },
  it:      { heading: '8. I tuoi diritti', body: 'Poiché non archiviamo dati su di te su alcun server, non c'è nulla da consultare, esportare o eliminare per tuo conto. Per rimuovere tutti i dati associati all'app, usa l'opzione di eliminazione nell'app o disinstalla Roulette de Movie dal tuo dispositivo.' },
  ko:      { heading: '8. 귀하의 권리',     body: '저희는 서버에 귀하에 관한 데이터를 저장하지 않으므로 귀하를 대신하여 접근, 내보내기 또는 삭제할 것이 없습니다. 앱과 관련된 모든 데이터를 제거하려면 앱 내 삭제 옵션을 사용하거나 기기에서 Roulette de Movie를 제거하십시오.' },
  'pt-PT': { heading: '8. Os Teus Direitos', body: 'Como não armazenamos dados sobre ti em nenhum servidor, não há nada para aceder, exportar ou eliminar em teu nome. Para remover todos os dados associados à aplicação, usa a opção de eliminação dentro da aplicação ou desinstala o Roulette de Movie do teu dispositivo.' },
  es:      { heading: '8. Tus Derechos',   body: 'Como no almacenamos datos sobre ti en ningún servidor, no hay nada que acceder, exportar o eliminar en tu nombre. Para eliminar todos los datos asociados a la aplicación, usa la opción de eliminación dentro de la aplicación o desinstala Roulette de Movie de tu dispositivo.' }
};
